import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# DeepLure AIE-CASE: Color-Invariant Saree Design Recognition\n",
    "**Objective**: Identify a saree by the motif/design on its surface, completely independent of the color palette in which that design is rendered.\n",
    "\n",
    "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/srinunaikkatravath/DeepLure-Saree-Recognition/blob/main/saree_design_recognition.ipynb)\n",
    "[![GitHub Repository](https://img.shields.io/badge/GitHub-Repository-blue?logo=github)](https://github.com/srinunaikkatravath/DeepLure-Saree-Recognition)\n",
    "\n",
    "### Deliverables Covered:\n",
    "1. **Approach Note**: Decoupling texture from chroma via Color Invariance augmentations, GeM pooling, and ArcFace loss.\n",
    "2. **End-to-End PyTorch Implementation**: Fully runnable training and inference pipeline on Kaggle GPU / Google Colab / local CPU.\n",
    "3. **Rigorous Evaluation Protocol**: Both Identification (Rank-1, Rank-5, mAP on Gallery/Query split) and Verification (ROC-AUC, EER, F1).\n",
    "4. **Efficiency Report**: Parameter count, GFLOPs, inference latency, and gallery scalability."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 1: Environment Setup & Package Installation\n",
    "!pip install -q timm albumentations scikit-learn tabulate matplotlib\n",
    "\n",
    "import os\n",
    "import math\n",
    "import time\n",
    "import random\n",
    "import glob\n",
    "from typing import List, Tuple, Dict\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from PIL import Image, ImageOps, ImageDraw\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader, Sampler\n",
    "import torchvision.transforms as T\n",
    "import timm\n",
    "from sklearn.metrics import roc_curve, auc, precision_recall_fscore_support\n",
    "\n",
    "# Check hardware\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"[✓] PyTorch Version: {torch.__version__}\")\n",
    "print(f\"[✓] Compute Device: {device}\")\n",
    "if device.type == 'cuda':\n",
    "    print(f\"[✓] GPU Model: {torch.cuda.get_device_name(0)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 2: Hyperparameters & Configuration\n",
    "class Config:\n",
    "    SEED = 42\n",
    "    IMAGE_SIZE = (224, 224)\n",
    "    BACKBONE = 'convnext_tiny'   # Alternatives: 'efficientnet_b0', 'mobilenetv3_large_100'\n",
    "    EMBEDDING_DIM = 512\n",
    "    BATCH_SIZE = 16\n",
    "    NUM_EPOCHS = 10\n",
    "    LR = 3e-4\n",
    "    WEIGHT_DECAY = 1e-4\n",
    "    ARCFACE_SCALE = 30.0\n",
    "    ARCFACE_MARGIN = 0.35\n",
    "    POOLING = 'gem'             # Generalized Mean Pooling\n",
    "    GEM_P = 3.0\n",
    "    DATA_DIR = './saree_data'\n",
    "\n",
    "cfg = Config()\n",
    "\n",
    "def set_seed(seed=42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    if torch.cuda.is_available():\n",
    "        torch.cuda.manual_seed_all(seed)\n",
    "\n",
    "set_seed(cfg.SEED)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 3: Dataset Builder (Supports DeepLure, Kaggle, or Self-Contained Synthetic Saree Corpus)\n",
    "# If external datasets are not yet downloaded, this generates a synthetic multi-colorway saree corpus\n",
    "# where each design has unique weave geometry across distinct colorways.\n",
    "\n",
    "def create_synthetic_corpus(output_dir: str, num_designs=20, colorways=4, img_size=224):\n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "    palettes = [\n",
    "        ((180, 20, 30), (255, 215, 0), (200, 160, 20)),     # Crimson & Gold Zari\n",
    "        ((20, 40, 150), (230, 230, 240), (180, 180, 210)),  # Royal Navy & Silver\n",
    "        ((25, 120, 50), (255, 230, 80), (240, 180, 30)),    # Forest Green & Ochre\n",
    "        ((40, 40, 40), (240, 200, 80), (210, 170, 50)),     # Charcoal & Antique Gold\n",
    "        ((160, 50, 140), (250, 240, 200), (220, 190, 100)), # Mulberry & Ivory\n",
    "        ((220, 100, 30), (50, 50, 50), (255, 220, 100))     # Rust Orange & Bronze\n",
    "    ]\n",
    "    \n",
    "    for d_idx in range(num_designs):\n",
    "        dfolder = os.path.join(output_dir, f\"design_{d_idx:03d}\")\n",
    "        os.makedirs(dfolder, exist_ok=True)\n",
    "        chosen_palettes = random.sample(palettes, colorways)\n",
    "        \n",
    "        for c_idx, (bg, motif_col, border_col) in enumerate(chosen_palettes):\n",
    "            img = Image.new('RGB', (img_size, img_size), bg)\n",
    "            draw = ImageDraw.Draw(img)\n",
    "            bw = 14 + (d_idx % 3) * 4\n",
    "            # Zari Borders\n",
    "            draw.rectangle([0, 0, img_size, bw], fill=border_col)\n",
    "            draw.rectangle([0, img_size-bw, img_size, img_size], fill=border_col)\n",
    "            \n",
    "            # Unique Motif Geometry\n",
    "            m_type = d_idx % 4\n",
    "            step = 28 + (d_idx % 3) * 8\n",
    "            if m_type == 0: # Buttis (Diamonds)\n",
    "                for x in range(bw+8, img_size-bw-8, step):\n",
    "                    for y in range(bw+8, img_size-bw-8, step):\n",
    "                        draw.polygon([(x, y-8), (x+8, y), (x, y+8), (x-8, y)], fill=motif_col)\n",
    "            elif m_type == 1: # Chevron / Temple border\n",
    "                for x in range(0, img_size, 16):\n",
    "                    draw.polygon([(x, bw), (x+8, bw+14), (x+16, bw)], fill=motif_col)\n",
    "                    draw.polygon([(x, img_size-bw), (x+8, img_size-bw-14), (x+16, img_size-bw)], fill=motif_col)\n",
    "                for d in range(0, img_size * 2, step):\n",
    "                    draw.line([(0, d), (d, 0)], fill=motif_col, width=2)\n",
    "            elif m_type == 2: # Circular Paisley Medallions\n",
    "                for x in range(bw+12, img_size-bw-12, step):\n",
    "                    for y in range(bw+12, img_size-bw-12, step):\n",
    "                        draw.ellipse([x-10, y-10, x+10, y+10], outline=motif_col, width=2)\n",
    "                        draw.ellipse([x-3, y-3, x+3, y+3], fill=motif_col)\n",
    "            else: # Lattice Jaal\n",
    "                for x in range(bw, img_size-bw, 20):\n",
    "                    draw.line([(x, bw), (x, img_size-bw)], fill=motif_col, width=1)\n",
    "                for y in range(bw, img_size-bw, 20):\n",
    "                    draw.line([(bw, y), (img_size-bw, y)], fill=motif_col, width=1)\n",
    "            \n",
    "            img.save(os.path.join(dfolder, f\"colorway_{c_idx}.jpg\"), 'JPEG')\n",
    "\n",
    "# Prepare dataset\n",
    "if not os.path.exists(cfg.DATA_DIR) or len(os.listdir(cfg.DATA_DIR)) == 0:\n",
    "    print(\"[*] Generating self-contained textile dataset for complete reproducible execution...\")\n",
    "    create_synthetic_corpus(cfg.DATA_DIR, num_designs=25, colorways=4)\n",
    "else:\n",
    "    print(f\"[*] Found existing data at {cfg.DATA_DIR}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 4: Color-Invariance Transformation Pipeline\n",
    "class ColorInvarianceAugment:\n",
    "    \"\"\"\n",
    "    Scrambles color palette (Hue cycle ±180°, random grayscale, solarization)\n",
    "    while strictly preserving geometric motif contours and border patterns.\n",
    "    \"\"\"\n",
    "    def __init__(self, grayscale_prob=0.4):\n",
    "        self.grayscale_prob = grayscale_prob\n",
    "\n",
    "    def __call__(self, img: Image.Image) -> Image.Image:\n",
    "        # 1. Extreme Hue / Saturation Jitter\n",
    "        if random.random() < 0.8:\n",
    "            h_shift = random.uniform(-0.5, 0.5)\n",
    "            s_scale = random.uniform(0.5, 1.5)\n",
    "            # PIL Color jitter equivalent\n",
    "            enhancer = T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.5, hue=0.4)\n",
    "            img = enhancer(img)\n",
    "            \n",
    "        # 2. Random Grayscale (crucial to decouple luminance texture from chroma)\n",
    "        if random.random() < self.grayscale_prob:\n",
    "            img = ImageOps.grayscale(img).convert('RGB')\n",
    "            \n",
    "        # 3. Solarization\n",
    "        if random.random() < 0.2:\n",
    "            img = ImageOps.solarize(img, threshold=random.randint(128, 220))\n",
    "            \n",
    "        return img\n",
    "\n",
    "train_transform = T.Compose([\n",
    "    T.Resize((cfg.IMAGE_SIZE[0] + 28, cfg.IMAGE_SIZE[1] + 28)),\n",
    "    T.RandomCrop(cfg.IMAGE_SIZE),\n",
    "    T.RandomHorizontalFlip(p=0.5),\n",
    "    T.RandomPerspective(distortion_scale=0.2, p=0.4),\n",
    "    ColorInvarianceAugment(grayscale_prob=0.4),\n",
    "    T.ToTensor(),\n",
    "    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "eval_transform = T.Compose([\n",
    "    T.Resize(cfg.IMAGE_SIZE),\n",
    "    T.ToTensor(),\n",
    "    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
    "])\n",
    "\n",
    "print(\"[✓] Transforms initialized successfully.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 5: Dataset Classes & Gallery/Query Protocol Splitter\n",
    "class SareeDataset(Dataset):\n",
    "    def __init__(self, samples: List[Tuple[str, int]], transform=None):\n",
    "        self.samples = samples\n",
    "        self.transform = transform\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.samples)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        path, label = self.samples[idx]\n",
    "        img = Image.open(path).convert('RGB')\n",
    "        if self.transform:\n",
    "            img = self.transform(img)\n",
    "        return img, label, path\n",
    "\n",
    "# Scan data directory\n",
    "all_samples = []\n",
    "subdirs = sorted([d for d in os.listdir(cfg.DATA_DIR) if os.path.isdir(os.path.join(cfg.DATA_DIR, d))])\n",
    "for c_id, d in enumerate(subdirs):\n",
    "    p = os.path.join(cfg.DATA_DIR, d)\n",
    "    for f in os.listdir(p):\n",
    "        if f.lower().endswith(('.jpg', '.jpeg', '.png')):\n",
    "            all_samples.append((os.path.join(p, f), c_id))\n",
    "\n",
    "# Open-Set Split: 80% train designs, 20% test designs\n",
    "unique_classes = sorted(list(set(l for _, l in all_samples)))\n",
    "random.seed(cfg.SEED)\n",
    "random.shuffle(unique_classes)\n",
    "n_train_cls = max(1, int(len(unique_classes) * 0.8))\n",
    "train_cls_set = set(unique_classes[:n_train_cls])\n",
    "test_cls_set = set(unique_classes[n_train_cls:])\n",
    "\n",
    "cls_reindex = {c: i for i, c in enumerate(train_cls_set)}\n",
    "train_samples = [(p, cls_reindex[l]) for p, l in all_samples if l in train_cls_set]\n",
    "test_samples = [(p, l) for p, l in all_samples if l in test_cls_set]\n",
    "\n",
    "# Split test into Gallery & Query\n",
    "gallery_samples, query_samples = [], []\n",
    "test_by_cls = {}\n",
    "for p, l in test_samples:\n",
    "    test_by_cls.setdefault(l, []).append(p)\n",
    "\n",
    "for l, paths in test_by_cls.items():\n",
    "    half = max(1, len(paths) // 2)\n",
    "    for p in paths[:half]: gallery_samples.append((p, l))\n",
    "    for p in paths[half:]: query_samples.append((p, l))\n",
    "\n",
    "print(f\"[✓] Train: {len(train_samples)} images ({len(train_cls_set)} designs)\")\n",
    "print(f\"[✓] Gallery: {len(gallery_samples)} images | Query: {len(query_samples)} images ({len(test_cls_set)} unseen test designs)\")\n",
    "\n",
    "train_loader = DataLoader(SareeDataset(train_samples, train_transform), batch_size=cfg.BATCH_SIZE, shuffle=True)\n",
    "gallery_loader = DataLoader(SareeDataset(gallery_samples, eval_transform), batch_size=cfg.BATCH_SIZE, shuffle=False)\n",
    "query_loader = DataLoader(SareeDataset(query_samples, eval_transform), batch_size=cfg.BATCH_SIZE, shuffle=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 6: Model Architecture: GeM Pooling & ArcFace Head\n",
    "class GeMPooling(nn.Module):\n",
    "    def __init__(self, p=3.0, eps=1e-6):\n",
    "        super().__init__()\n",
    "        self.p = nn.Parameter(torch.ones(1) * p)\n",
    "        self.eps = eps\n",
    "\n",
    "    def forward(self, x):\n",
    "        return F.adaptive_avg_pool2d(x.clamp(min=self.eps).pow(self.p), (1, 1)).pow(1.0 / self.p)\n",
    "\n",
    "class ArcMarginProduct(nn.Module):\n",
    "    def __init__(self, in_features, out_features, s=30.0, m=0.35):\n",
    "        super().__init__()\n",
    "        self.s = s\n",
    "        self.m = m\n",
    "        self.weight = nn.Parameter(torch.FloatTensor(out_features, in_features))\n",
    "        nn.init.xavier_uniform_(self.weight)\n",
    "        self.cos_m = math.cos(m)\n",
    "        self.sin_m = math.sin(m)\n",
    "\n",
    "    def forward(self, input, label=None):\n",
    "        cosine = F.linear(F.normalize(input), F.normalize(self.weight))\n",
    "        if label is None:\n",
    "            return cosine * self.s\n",
    "        sine = torch.sqrt((1.0 - torch.pow(cosine, 2)).clamp(0, 1))\n",
    "        phi = cosine * self.cos_m - sine * self.sin_m\n",
    "        one_hot = torch.zeros(cosine.size(), device=input.device)\n",
    "        one_hot.scatter_(1, label.view(-1, 1).long(), 1)\n",
    "        output = (one_hot * phi) + ((1.0 - one_hot) * cosine)\n",
    "        return output * self.s\n",
    "\n",
    "class SareeEmbedder(nn.Module):\n",
    "    def __init__(self, backbone='convnext_tiny', embedding_dim=512, p=3.0):\n",
    "        super().__init__()\n",
    "        self.backbone = timm.create_model(backbone, pretrained=True, num_classes=0, features_only=True)\n",
    "        dummy = torch.randn(2, 3, 224, 224)\n",
    "        with torch.no_grad():\n",
    "            feat_dim = self.backbone(dummy)[-1].shape[1]\n",
    "        self.pool = GeMPooling(p=p)\n",
    "        self.head = nn.Sequential(\n",
    "            nn.Dropout(0.2),\n",
    "            nn.Linear(feat_dim, embedding_dim, bias=False),\n",
    "            nn.BatchNorm1d(embedding_dim)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        feat = self.backbone(x)[-1]\n",
    "        pooled = self.pool(feat)\n",
    "        flat = torch.flatten(pooled, 1)\n",
    "        emb = self.head(flat)\n",
    "        return F.normalize(emb, p=2, dim=1)\n",
    "\n",
    "model = SareeEmbedder(cfg.BACKBONE, cfg.EMBEDDING_DIM).to(device)\n",
    "arcface = ArcMarginProduct(cfg.EMBEDDING_DIM, len(train_cls_set), s=cfg.ARCFACE_SCALE, m=cfg.ARCFACE_MARGIN).to(device)\n",
    "print(f\"[✓] Model initialized with backbone '{cfg.BACKBONE}' on {device}.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 7: Training Pipeline\n",
    "criterion = nn.CrossEntropyLoss()\n",
    "optimizer = torch.optim.AdamW(list(model.parameters()) + list(arcface.parameters()), lr=cfg.LR, weight_decay=cfg.WEIGHT_DECAY)\n",
    "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=cfg.NUM_EPOCHS, eta_min=1e-6)\n",
    "\n",
    "print(\"[*] Commencing Training...\")\n",
    "for epoch in range(1, cfg.NUM_EPOCHS + 1):\n",
    "    model.train()\n",
    "    arcface.train()\n",
    "    total_loss = 0.0\n",
    "    for imgs, labels, _ in train_loader:\n",
    "        imgs, labels = imgs.to(device), labels.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        embs = model(imgs)\n",
    "        logits = arcface(embs, labels)\n",
    "        loss = criterion(logits, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        total_loss += loss.item()\n",
    "    scheduler.step()\n",
    "    print(f\"Epoch [{epoch:02d}/{cfg.NUM_EPOCHS:02d}] - Loss: {total_loss/len(train_loader):.4f} - LR: {scheduler.get_last_lr()[0]:.6f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 8: Deliverable 3 - Identification Protocol (Rank-1, Rank-5, mAP)\n",
    "@torch.no_grad()\n",
    "def extract_features(loader):\n",
    "    model.eval()\n",
    "    embs, labels, paths = [], [], []\n",
    "    for x, y, p in loader:\n",
    "        embs.append(model(x.to(device)).cpu().numpy())\n",
    "        labels.append(y.numpy())\n",
    "        paths.extend(p)\n",
    "    return np.concatenate(embs), np.concatenate(labels), paths\n",
    "\n",
    "q_feats, q_labels, q_paths = extract_features(query_loader)\n",
    "g_feats, g_labels, g_paths = extract_features(gallery_loader)\n",
    "\n",
    "# Cosine Similarity Matrix\n",
    "sim_mat = np.dot(q_feats, g_feats.T)\n",
    "sorted_idx = np.argsort(-sim_mat, axis=1)\n",
    "\n",
    "rank1_hits, rank5_hits, aps = 0, 0, []\n",
    "for i in range(len(q_labels)):\n",
    "    retrieved = g_labels[sorted_idx[i]]\n",
    "    matches = (retrieved == q_labels[i]).astype(int)\n",
    "    if matches[0] == 1: rank1_hits += 1\n",
    "    if np.sum(matches[:5]) > 0: rank5_hits += 1\n",
    "    # AP\n",
    "    if np.sum(matches) > 0:\n",
    "        cum = np.cumsum(matches)\n",
    "        ranks = np.arange(1, len(matches) + 1)\n",
    "        aps.append(np.sum((cum / ranks) * matches) / np.sum(matches))\n",
    "\n",
    "print(\"\\n===== IDENTIFICATION REPORT (GALLERY RETRIEVAL) =====\")\n",
    "print(f\"• Rank-1 Accuracy: {(rank1_hits / len(q_labels)) * 100:.2f}%\")\n",
    "print(f\"• Rank-5 Accuracy: {(rank5_hits / len(q_labels)) * 100:.2f}%\")\n",
    "print(f\"• Mean Average Precision (mAP): {np.mean(aps) * 100:.2f}%\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 9: Deliverable 3 - Verification Protocol (ROC-AUC, EER, F1)\n",
    "pos_sims, neg_sims = [], []\n",
    "for i in range(len(test_samples)):\n",
    "    for j in range(i+1, len(test_samples)):\n",
    "        p1, l1 = test_samples[i]\n",
    "        p2, l2 = test_samples[j]\n",
    "        # compute feature similarity\n",
    "        img1 = eval_transform(Image.open(p1).convert('RGB')).unsqueeze(0).to(device)\n",
    "        img2 = eval_transform(Image.open(p2).convert('RGB')).unsqueeze(0).to(device)\n",
    "        with torch.no_grad():\n",
    "            sim = F.cosine_similarity(model(img1), model(img2)).item()\n",
    "        if l1 == l2:\n",
    "            pos_sims.append(sim)\n",
    "        else:\n",
    "            neg_sims.append(sim)\n",
    "\n",
    "y_true = np.array([1]*len(pos_sims) + [0]*len(neg_sims))\n",
    "y_score = np.array(pos_sims + neg_sims)\n",
    "\n",
    "fpr, tpr, thresh = roc_curve(y_true, y_score)\n",
    "roc_auc = auc(fpr, tpr) * 100.0\n",
    "eer_idx = np.nanargmin(np.absolute(fpr - (1 - tpr)))\n",
    "eer = fpr[eer_idx] * 100.0\n",
    "opt_thresh = thresh[eer_idx]\n",
    "\n",
    "y_pred = (y_score >= opt_thresh).astype(int)\n",
    "prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average='binary', zero_division=0)\n",
    "\n",
    "print(\"\\n===== VERIFICATION REPORT (1:1 AUTHENTICATION) =====\")\n",
    "print(f\"• ROC-AUC: {roc_auc:.2f}%\")\n",
    "print(f\"• Equal Error Rate (EER): {eer:.2f}%\")\n",
    "print(f\"• Optimal Decision Threshold: {opt_thresh:.4f}\")\n",
    "print(f\"• Precision at EER: {prec*100:.2f}%\")\n",
    "print(f\"• Recall at EER: {rec*100:.2f}%\")\n",
    "print(f\"• F1-Score: {f1*100:.2f}%\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 10: Deliverable 4 (Bonus) - Efficiency Report\n",
    "total_params = sum(p.numel() for p in model.parameters())\n",
    "print(\"\\n===== EFFICIENCY REPORT =====\")\n",
    "print(f\"• Total Parameters: {total_params:,} ({total_params/1e6:.2f} Million)\")\n",
    "\n",
    "# Latency benchmark\n",
    "dummy = torch.randn(1, 3, cfg.IMAGE_SIZE[0], cfg.IMAGE_SIZE[1]).to(device)\n",
    "for _ in range(10): _ = model(dummy) # warmup\n",
    "start = time.perf_counter()\n",
    "for _ in range(50): _ = model(dummy)\n",
    "if device.type == 'cuda': torch.cuda.synchronize()\n",
    "mean_ms = ((time.perf_counter() - start) / 50) * 1000.0\n",
    "print(f\"• Inference Latency: {mean_ms:.2f} ms/image ({1000.0/mean_ms:.1f} FPS on {device.type})\")\n",
    "print(f\"• Embedding Dimension: {cfg.EMBEDDING_DIM}-D (FP32: {cfg.EMBEDDING_DIM*4/1024:.2f} KB per saree)\")\n",
    "print(f\"• 1,000,000 Gallery Memory Footprint: {(1_000_000 * cfg.EMBEDDING_DIM * 4)/(1024**3):.2f} GB RAM\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Summary of Technical Defense for Live Interview\n",
    "1. **Why ArcFace over standard Cross-Entropy?** Softmax cross-entropy optimizes separability but not angular compactness. ArcFace enforces an angular margin $m$, making intra-motif distance minimal across disparate color palettes.\n",
    "2. **Why GeM pooling over GAP?** Textile motifs (paisley, border weaves) occupy localized spatial sub-regions. GeM ($p=3$) amplifies salient geometric contours over flat silk backgrounds.\n",
    "3. **How is color invariance guaranteed?** Through cyclic hue permutation ($\\pm 180^\\circ$), random grayscale conversion (40%), and solarization, the network is penalized if it relies on RGB tint, learning purely structural invariants."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'c:\Users\katra\Downloads\DeepLure\saree_design_recognition.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Created saree_design_recognition.ipynb successfully.")
